### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by stevehorn** [CartoDB/Windshaft#369]
After installing all dependencies, and running `npm install` I get a series of failures like this:
```
npm ERR! Error: ENOENT, lstat '/root/repositories/Windshaft/node_modules/carto/node_modules/mapnik-reference/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/repositories/Windshaft
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/repositories/Windshaft/node_modules/carto/node_modules/mapnik-reference/README.md
npm ERR! fstream_path /root/repositories/Windshaft/node_modules/carto/node_modules/mapnik-reference/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open '/root/repositories/Windshaft/node_modules/carto/node_modules/optimist/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

npm -v = 1.3.10

Updated to npm -v 2.13.1 and got different errors (it appears to be trying to build/install sqlite3?):

```
root@Tile-Server:~/repositories/Windshaft# npm install
npm WARN package.json windshaft@0.48.1 No license field.
npm WARN cannot run in wd windshaft@0.48.1 make pre-install (wd=/root/repositories/Windshaft)
npm WARN engine chronograph@0.1.0: wanted: {"node":">= 0.8 < 0.11"} (current: {"node":"0.12.7","npm":"2.13.1"})
npm WARN engine millstone@0.6.14: wanted: {"node":"0.4 || 0.6 || 0.8 || 0.10"} (current: {"node":"0.12.7","npm":"2.13.1"})
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/bin/node --eval require('/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node')
/usr/local/bin/node: symbol lookup error: /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static void node_sqlite3::Database::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/database.cc:134:71: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
                                                                       ^
../src/database.cc:134:71: note: candidates are:
In file included from /root/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/database.cc:2:
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
   bool Set(Handle<Value> key, Handle<Value> value);
        ^
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
../src/database.cc:135:69: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Integer>, v8::PropertyAttribute)’
     args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
                                                                     ^
../src/database.cc:135:69: note: candidates are:
In file included from /root/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/database.cc:2:
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
   bool Set(Handle<Value> key, Handle<Value> value);
        ^
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/root/.node-gyp/0.12.7/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory `/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/repositories/Windshaft/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/root/repositories/Windshaft/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/lib/binding/node-v14-linux-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-linux-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz"
gyp ERR! cwd /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/lib/binding/node-v14-linux-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 3.13.0-57-generic
node-pre-gyp ERR! command "node" "/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/sqlite3/lib/binding/node-v14-linux-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-x64.tar.gz' (1)

> zipfile@0.5.7 install /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/zipfile
> node-pre-gyp install --fallback-to-build

make: Entering directory `/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/zipfile/build'
  ACTION deps_libzip_gyp_action_before_build_target_unpack_libzip_dep Release/obj/gen/libzip-0.11.1/lib/zip_add.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_add.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_add_dir.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_add_entry.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_close.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_delete.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_dir_add.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_dirent.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_discard.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_entry.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_err_str.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error_clear.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error_get.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error_get_sys_type.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error_strerror.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_error_to_str.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_extra_field.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_extra_field_api.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fclose.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fdopen.o
Release/obj/gen/libzip-0.11.1/lib/zip_fdopen.c: In function ‘zip_fdopen’:
Release/obj/gen/libzip-0.11.1/lib/zip_fdopen.c:62:5: warning: implicit declaration of function ‘dup’ [-Wimplicit-function-declaration]
     if ((fd=dup(fd_orig)) < 0) {
     ^
Release/obj/gen/libzip-0.11.1/lib/zip_fdopen.c:68:2: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
  close(fd);
  ^
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_add.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_error_clear.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_error_get.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_get_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_get_external_attributes.o
Release/obj/gen/libzip-0.11.1/lib/zip_file_get_external_attributes.c: In function ‘zip_file_get_external_attributes’:
Release/obj/gen/libzip-0.11.1/lib/zip_file_get_external_attributes.c:41:24: warning: unused variable ‘str’ [-Wunused-variable]
     const zip_uint8_t *str;
                        ^
Release/obj/gen/libzip-0.11.1/lib/zip_file_get_external_attributes.c:40:18: warning: unused variable ‘len’ [-Wunused-variable]
     zip_uint32_t len;
                  ^
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_get_offset.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_rename.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_replace.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_set_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_set_external_attributes.o
Release/obj/gen/libzip-0.11.1/lib/zip_file_set_external_attributes.c: In function ‘zip_file_set_external_attributes’:
Release/obj/gen/libzip-0.11.1/lib/zip_file_set_external_attributes.c:55:58: warning: signed and unsigned type in conditional expression [-Wsign-compare]
     unchanged_attributes = e->orig ? e->orig->ext_attrib : ZIP_EXT_ATTRIB_DEFAULT;
                                                          ^
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_file_strerror.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_filerange_crc.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fopen.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fopen_encrypted.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fopen_index.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fopen_index_encrypted.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_fread.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_archive_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_archive_flag.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_compression_implementation.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_encryption_implementation.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_file_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_name.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_num_entries.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_get_num_files.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_memdup.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_name_locate.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_new.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_open.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_rename.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_replace.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_archive_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_archive_flag.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_default_password.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_file_comment.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_file_compression.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_set_name.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_buffer.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_close.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_crc.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_deflate.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_error.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_file.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_filep.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_free.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_function.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_layered.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_open.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_pkware.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_pop.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_read.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_stat.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_window.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_zip.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_source_zip_new.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_stat.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_stat_index.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_stat_init.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_strerror.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_string.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_unchange.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_unchange_all.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_unchange_archive.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_unchange_data.o
  CC(target) Release/obj.target/libzip/gen/libzip-0.11.1/lib/zip_utf-8.o
  AR(target) Release/obj.target/deps/zip.a
  COPY Release/zip.a
  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/ioapi.o
  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/unzip.o
../deps/zlib/contrib/minizip/unzip.c: In function ‘unzlocal_getShort’:
../deps/zlib/contrib/minizip/unzip.c:215:7: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     x = (uLong)i;
       ^
../deps/zlib/contrib/minizip/unzip.c: In function ‘unzlocal_getLong’:
../deps/zlib/contrib/minizip/unzip.c:243:7: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     x = (uLong)i;
       ^
  CC(target) Release/obj.target/zlib/deps/zlib/contrib/minizip/zip.o
../deps/zlib/contrib/minizip/zip.c:196:12: warning: ‘free_linkedlist’ defined but not used [-Wunused-function]
 local void free_linkedlist(ll)
            ^
../deps/zlib/contrib/minizip/zip.c: In function ‘ziplocal_getShort’:
../deps/zlib/contrib/minizip/zip.c:384:7: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     x = (uLong)i;
       ^
../deps/zlib/contrib/minizip/zip.c: In function ‘ziplocal_getLong’:
../deps/zlib/contrib/minizip/zip.c:412:7: warning: ‘i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     x = (uLong)i;
       ^
  CC(target) Release/obj.target/zlib/deps/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/zlib/compress.o
  CC(target) Release/obj.target/zlib/deps/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzio.o
  CC(target) Release/obj.target/zlib/deps/zlib/infback.o
  CC(target) Release/obj.target/zlib/deps/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/zlib/inflate.o
  CC(target) Release/obj.target/zlib/deps/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/deps/zlib/zutil.o
  AR(target) Release/obj.target/deps/zlib/chrome_zlib.a
  COPY Release/chrome_zlib.a
  CXX(target) Release/obj.target/zipfile/src/node_zipfile.o
  SOLINK_MODULE(target) Release/obj.target/zipfile.node
  COPY Release/zipfile.node
  COPY /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/zipfile/lib/binding/node-v14-linux-x64/zipfile.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/zipfile/build'

> srs@0.4.8 install /root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs
> node-pre-gyp install --fallback-to-build

[srs] Success: "/root/repositories/Windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs/lib/binding/node-v14-linux-x64/srs.node" is installed via remote
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/repositories/Windshaft/npm-debug.log
```

**Comment by stevehorn** [comment]
Traced this to my version of node. Switched from node v0.12.7 to v0.10.40 and build worked.
