### ISSUE TITLE
14 failing test on "make check"

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#495]
With current master, failures detail:

```
  480 passing (15s)
  7 pending
  14 failing

  1) external resources "before each" hook:
     Error: ENOENT, no such file or directory '/tmp/windshaft-test/millstone'
      at Object.fs.readdirSync (fs.js:654:18)
      at rmdir_recursive_sync (/usr/src/node/modules/Windshaft/test/acceptance/external_resources.js:12:18)
      at Context.<anonymous> (/usr/src/node/modules/Windshaft/test/acceptance/external_resources.js:36:9)
      at Hook.Runnable.run (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runnable.js:217:15)
      at next (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runner.js:258:10)
      at Object._onImmediate (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  2) external resources "after each" hook:
     TypeError: Cannot call method 'close' of undefined
      at Context.<anonymous> (/usr/src/node/modules/Windshaft/test/acceptance/external_resources.js:59:25)
      at Hook.Runnable.run (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runnable.js:217:15)
      at next (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runner.js:258:10)
      at Object._onImmediate (/usr/src/node/modules/Windshaft/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  3) torque png renderer tiles should support marker-file with url:
     Uncaught 
  AssertionError: Error: Images are not similar (got 0.044952392578125 similarity, expected 0.02)
      at /usr/src/node/modules/Windshaft/test/acceptance/torque_png.js:147:36
      at /usr/src/node/modules/Windshaft/test/support/assert.js:102:9
      at imagesAreSimilar (/usr/src/node/modules/Windshaft/test/support/assert.js:146:9)
      at Function.assert.imageEqualsFile (/usr/src/node/modules/Windshaft/test/support/assert.js:96:5)
      at /usr/src/node/modules/Windshaft/test/acceptance/torque_png.js:146:32
      at /usr/src/node/modules/Windshaft/test/support/assert.js:102:9
      at imagesAreSimilar (/usr/src/node/modules/Windshaft/test/support/assert.js:146:9)
      at Function.assert.imageEqualsFile (/usr/src/node/modules/Windshaft/test/support/assert.js:96:5)
      at /usr/src/node/modules/Windshaft/test/acceptance/torque_png.js:144:24
      at /usr/src/node/modules/Windshaft/test/support/test_client.js:87:16
      at Function.<anonymous> (/usr/src/node/modules/Windshaft/lib/windshaft/backends/tile.js:61:13)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at /usr/src/node/modules/Windshaft/lib/windshaft/renderers/base_adaptor.js:17:28
      at /usr/src/node/modules/Windshaft/lib/windshaft/renderers/torque/png_renderer.js:100:21

  4) static_maps center image:
     Error: Postgis Plugin: Bad connection
Connection string: ' dbname=windshaft_test user=postgres connect_timeout=4'
  encountered during parsing of layer 'layer0' in Layer


  5) static_maps center image with invalid basemap:
     Error: Postgis Plugin: Bad connection
Connection string: ' dbname=windshaft_test user=postgres connect_timeout=4'
  encountered during parsing of layer 'layer0' in Layer


  6) static_maps bbox:
     Error: Postgis Plugin: Bad connection
Connection string: ' dbname=windshaft_test user=postgres connect_timeout=4'
  encountered during parsing of layer 'layer0' in Layer


  7) static_maps should not fail for coordinates out of range:
     Error: Postgis Plugin: Bad connection
Connection string: ' dbname=windshaft_test user=postgres connect_timeout=4'
  encountered during parsing of layer 'layer0' in Layer


  8) static_maps should keep failing for other errors:  
     Uncaught AssertionError: null == true
      at /usr/src/node/modules/Windshaft/test/integration/static_maps.js:215:20
      at Function.handleImage (/usr/src/node/modules/Windshaft/lib/windshaft/backends/preview.js:71:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at rendererGetTileQueueFinish (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/blend/factory.js:103:20)
      at notify (/usr/src/node/modules/Windshaft/node_modules/queue-async/queue.js:45:26)
      at /usr/src/node/modules/Windshaft/node_modules/queue-async/queue.js:35:11
      at cb (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/blend/factory.js:54:28)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  9) render_cache can generate a tilelive object:
     Uncaught TypeError: Cannot call method 'get' of undefined
      at EventEmitter.CacheEntry.get (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:34:26)
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:104:32
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  10) render_cache can generate > 1 tilelive object:
     Uncaught AssertionError: 1 == 2
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:117:24
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  11) render_cache can delete all tilelive objects when reset:
     Uncaught AssertionError: 1 == 2
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:145:24
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  12) render_cache can delete only related tilelive objects when reset:
     Uncaught AssertionError: 1 == 3
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:164:28
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  13) render_cache clears both auth and non-auth renderer caches on reset:
     Uncaught AssertionError: 2 == 3
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:195:28
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)

  14) render_cache can purge all tilelive objects:
     Uncaught AssertionError: 1 == 3
      at /usr/src/node/modules/Windshaft/test/unit/render_cache.test.js:220:28
      at EventEmitter.CacheEntry.setReady (/usr/src/node/modules/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/renderer_factory.js:98:20)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/usr/src/node/modules/Windshaft/lib/windshaft/renderers/mapnik/factory.js:245:13)
      at MapnikSource.next (/usr/src/node/modules/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.EventEmitter.emit (events.js:95:17)
      at /usr/src/node/modules/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:142:20
      at process._tickCallback (node.js:415:13)



Cleaning up
make: *** [test] Error 14
```

**Comment by strk** [comment]
Current master being 2500e8a419e28cc543e768531a4b0353b190818d - PostgreSQL version 9.3.6 (if that matters) - and postgis version in windshaft_test by the end of `make check` is  ``POSTGIS="2.3.0dev r14989" GEOS="3.6.0dev-CAPI-1.10.0 r4218" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 2.2.0dev, released 2016/99/99" LIBXML="2.9.1" LIBJSON="0.12" RASTER``

**Comment by strk** [comment]
Installed Mapnik is 3.0.10 and npm is 3.8.1 (NOTE: the README.md file says npm must be `>=1.2.1 <2.0.0`, but I suspect it is outdated).

**Comment by strk** [comment]
On re-running `make check` I get only 12 failures. I think this is due to some tests expecting existance of some temporary directories which are created by other tests (see first failure in my original submission).

**Comment by rochoa** [comment]
Did you check with mapnik `>2.0.0 <3.0.0`?

**Comment by strk** [comment]
Nope, I hadn't.
BTW: the README.md file contains a reference to an unexisting ``#installing-mapnik`` anchor

**Comment by strk** [comment]
Now I did, same behavior (14 failures on first run, 12 on second)

**Comment by strk** [comment]
with mapnik 2.3.x manually built on an ubuntu 14.04

**Comment by strk** [comment]
The `Bad connection` message is due to forcing `user=postgres` in the test (other tests are fine):
```
test/integration/static_maps.js:101:            dbuser: 'postgres',
```

Deleting that line (101) fixes those tests for me, reducing failures to 6.
@rochoa do you want a pull request for this one ?

**Comment by rochoa** [comment]
Yes, please.

**Comment by strk** [comment]
Done already @rochoa : #502

**Comment by rochoa** [comment]
So, is this still happening?

**Comment by strk** [comment]
Still happening:
http://strk.kbt.io/tmp/log

Sorry for ANSI colors in the log but that's what "make check"
outputs...

**Comment by rochoa** [comment]
Can you check you have the right permissions for https://github.com/CartoDB/Windshaft/blob/7f3909d7fb4aeed58f847e8a87167bf83d1ea968/config/environments/test.js#L13?

**Comment by strk** [comment]
Directory pointed by `cache_basedir` is all owned by myself

**Comment by Algunenano** [comment]
No longer applicable
